### ISSUE TITLE
👓 avances

### ISSUE THREAD

**Issue by anattolia** [enflujo/unal-cuenco#2]
@1cgonza No tengo preguntas puntuales por ahora pero he avanzado con el procesador y en la página de inicio se ven las listas de las variables de las publicaciones y la cantidad de publicaciones por cada una.

No sé si quieres darle una mirada general. Algunos de los campos falta limpiarlos o separarlos mejor, como las fuentes.

**Comment by 1cgonza** [comment]
@anattolia voy a revisar y voy creando "issues" para desagregar las tareas de esto. Si quieres vas creando lo que puedas anticipar de lo que dices que falta.
