### ISSUE TITLE
🐞 En Colectivos faltan los indicadores?

### ISSUE THREAD

**Issue by anattolia** [enflujo/unal-cuenco#27]
Creo que en Colectivos faltan los indicadores, ¿puede ser?

Sí están en la lista pero en colectivos.json no los veo.

**Comment by 1cgonza** [comment]
@anattolia tienes razón, ya quedaron en este cambio [c3b27d8](https://github.com/enflujo/unal-cuenco/commit/c3b27d853f06dc1014331afa407621fbab2d9a0d)

Para que sepas, ese campo tiene el id del indicador y no es de tipo `DefinicionSimple` o `DefinicionSimple[]` como en los otros campos.

En este ejemplo **dependencias** es `DefinicionSimple`, **sedes** es `DefinicionSimple[]`, e **indicador** es el _número_ del id:

```json
{
  "dependencias":{"nombre":"Ministerio de Educación","slug":"ministerio-de-educacion"},
  "sedes":[{"nombre":"Bogotá","slug":"bogota"}, {"nombre":"Manizales","slug":"manizales"}],
  "indicadores":38
}
```

Esto lo puse con _ids_  porque el JSON estaba quedando muy pesado.
