### ISSUE TITLE
🔧 Orden de ejecución

### ISSUE THREAD

**Issue by 1cgonza** [enflujo/unal-cuenco#4]
## Cuando guardar JSON

Ahora se están generando los `.json` al procesar cada fila, en una tabla pequeña y con procesos ligeros no se nota, pero a medida que crece la complejidad, esto va a generar impacto en el uso de recursos ya que generar los json es pesado. 

La solución en mover los `guardarJSON()`  dentro de `close` y antes de `resolver()`. 

## Cuando resolver

`resolver()` debería ser lo último del proceso, acá se resuelve y luego se van a construir las relaciones. En este momento, esas relaciones no van a quedar en los JSON ya que se crean los JSON antes de construir las relaciones. 

```js
resolver();

if (!filasPreprocesadas && totalFilas === filasProcesadas) {
  filasPreprocesadas = true;
  construirRelacionesDePublicaciones();
}
```

## Orden en abstracto

1. procesar filas
2. procesar relaciones
3. guardar json
4. resolver

**Comment by anattolia** [comment]
@1cgonza gracias por la aclaración. Lo cambié en una rama nueva.
